/**
 * Wings simulator — full implementation.
 *
 * In-process mock of the Wings daemon. Activated when MOCK_WINGS=true.
 * Provides:
 *   - Realistic Paper 1.21.4 boot sequence with proper timing
 *   - State machine: offline → starting → online → stopping → offline
 *   - CPU/RAM stats that drift realistically (spikes on startup, drifts when online)
 *   - Console event bus (any subscriber gets every emitted line)
 *   - 1000-line ring buffer for log replay on "request logs"
 *   - Command handling: list, help, tps, say, time, weather, stop, etc.
 *   - In-memory virtual file system pre-seeded with realistic server files
 *   - Backup simulation
 */

import type {
  WingsDirectoryContents,
  WingsServerState,
  WingsConsoleAuth,
  WingsBackup,
} from "./types";
import type { PowerAction } from "./types";

// ── Types ─────────────────────────────────────────────────────────────────────

type SimStatus = "running" | "offline" | "starting" | "stopping";

interface SimServer {
  status: SimStatus;
  cpu: number;          // percent
  memBytes: number;
  diskBytes: number;
  netRx: number;
  netTx: number;
  startedAt: number | null;
  onlinePlayerCount: number;
  tickInterval: ReturnType<typeof setInterval> | null;
}

// ── Shared state ──────────────────────────────────────────────────────────────
// Anchored to globalThis so Next.js API routes (webpack module context) and
// server.ts (Node native require) share the same Maps — prevents the split
// where power() fires in one instance but onConsole() is registered in another.

type SimGlobal = {
  _simServers: Map<string, SimServer>;
  _simLogBuffers: Map<string, string[]>;
  _simConsoleListeners: Map<string, Set<(line: string) => void>>;
  _simVirtualFs: Map<string, Map<string, string>>;
};

const g = globalThis as typeof globalThis & Partial<SimGlobal>;

const servers: Map<string, SimServer> = g._simServers ?? (g._simServers = new Map());
const logBuffers: Map<string, string[]> = g._simLogBuffers ?? (g._simLogBuffers = new Map());
const consoleListeners: Map<string, Set<(line: string) => void>> = g._simConsoleListeners ?? (g._simConsoleListeners = new Map());
const virtualFs: Map<string, Map<string, string>> = g._simVirtualFs ?? (g._simVirtualFs = new Map());

const LOG_CAP = 1000;

// ── Helpers ───────────────────────────────────────────────────────────────────

function getServer(uuid: string): SimServer {
  if (!servers.has(uuid)) {
    servers.set(uuid, {
      status: "offline",
      cpu: 0,
      memBytes: 0,
      diskBytes: Math.round((1.2 + Math.random() * 0.6) * 1024 * 1024 * 1024),
      netRx: 0,
      netTx: 0,
      startedAt: null,
      onlinePlayerCount: 0,
      tickInterval: null,
    });
  }
  return servers.get(uuid)!;
}

function pushLog(uuid: string, line: string) {
  let buf = logBuffers.get(uuid);
  if (!buf) {
    buf = [];
    logBuffers.set(uuid, buf);
  }
  buf.push(line);
  if (buf.length > LOG_CAP) buf.shift();
  emit(uuid, line);
}

function emit(uuid: string, line: string) {
  const listeners = consoleListeners.get(uuid);
  if (!listeners) return;
  for (const cb of Array.from(listeners)) cb(line);
}

function ts() {
  const d = new Date();
  const hh = String(d.getHours()).padStart(2, "0");
  const mm = String(d.getMinutes()).padStart(2, "0");
  const ss = String(d.getSeconds()).padStart(2, "0");
  return `[${hh}:${mm}:${ss}`;
}

function log(uuid: string, level: "INFO" | "WARN" | "ERROR", msg: string) {
  pushLog(uuid, `${ts()} ${level}]: ${msg}`);
}

function delay(ms: number) {
  return new Promise<void>((r) => setTimeout(r, ms));
}

// ── Virtual file system ───────────────────────────────────────────────────────

const SERVER_PROPERTIES = `#Minecraft server properties
#Generated by HobbyPanel simulator
enable-jmx-monitoring=false
rcon.port=25575
level-seed=
gamemode=survival
enable-command-block=false
enable-query=false
generator-settings={}
enforce-secure-profile=true
level-name=world
motd=A Minecraft Server
query.port=25565
pvp=true
generate-structures=true
max-chained-neighbor-updates=1000000
difficulty=easy
network-compression-threshold=256
max-tick-time=60000
require-resource-pack=false
use-native-transport=true
max-players=20
online-mode=true
enable-status=true
allow-flight=false
broadcast-rcon-to-ops=true
view-distance=10
server-ip=
resource-pack-prompt=
allow-nether=true
server-port=25565
enable-rcon=false
sync-chunk-writes=true
op-permission-level=4
prevent-proxy-connections=false
hide-online-players=false
resource-pack=
entity-broadcast-range-percentage=100
simulation-distance=10
rcon.password=
player-idle-timeout=0
force-gamemode=false
rate-limit=0
hardcore=false
white-list=false
broadcast-console-to-ops=true
spawn-npcs=true
spawn-animals=true
log-ips=true
function-permission-level=2
initial-disabled-packs=
level-type=minecraft\\:normal
text-filtering-config=
spawn-monsters=true
enforce-whitelist=false
spawn-protection=16
resource-pack-sha1=
max-world-size=29999984
`;

const SPIGOT_YML = `# This is the main configuration file for Spigot.
# As you can see, there's tons to configure. Some options may impact gameplay,
# so use with caution and make sure you know what each option does before changing it.
settings:
  debug: false
  bungeecord: false
  sample-count: 12
  player-shuffle: 0
  user-cache-size: 1000
  save-user-cache-on-stop-only: false
  moved-wrongly-threshold: 0.0625
  moved-too-quickly-multiplier: 10.0
  timeout-time: 60
  restart-on-crash: true
  restart-script: ./start.sh
  netty-threads: 4
  attribute:
    maxHealth:
      max: 2048.0
    movementSpeed:
      max: 2048.0
    attackDamage:
      max: 2048.0
  log-villager-deaths: true
  log-named-deaths: true
messages:
  whitelist: You are not whitelisted on this server!
  unknown-command: Unknown command. Type "/help" for help.
  server-full: The server is full!
  outdated-client: Outdated client! Please use {0}
  outdated-server: "Outdated server! I'm still on {0}"
  restart: Server is restarting
`;

const PAPER_YML = `# This is the main configuration file for Paper.
# As you can see, there's tons to configure. Some options may impact gameplay, so
# use with caution, and make sure you know what each option does before changing it.
_version: 28
verbose: false
timings:
  enabled: true
  verbose: true
  server-name-privacy: false
  hidden-config-entries:
    - database
    - settings.bungeecord-addresses
    - settings.velocity-secret
  history-interval: 300
  history-length: 3600
  server-name: Unknown Server
`;

const EULA_TXT = `#By changing the setting below to TRUE you are indicating your agreement to our EULA (https://aka.ms/MinecraftEULA).
#Generated by HobbyPanel simulator
eula=true
`;

const SAMPLE_LOG = `[00:00:01 INFO]: Starting minecraft server version 1.21.4
[00:00:01 INFO]: Loading properties
[00:00:01 INFO]: This server is running Paper version git-Paper-196 (MC: 1.21.4)
[00:00:08 INFO]: Done (7.3s)! For help, type "help"
`;

function buildFs(uuid: string): Map<string, string> {
  const fs = new Map<string, string>();
  fs.set("/server.properties", SERVER_PROPERTIES);
  fs.set("/spigot.yml", SPIGOT_YML);
  fs.set("/paper.yml", PAPER_YML);
  fs.set("/eula.txt", EULA_TXT);
  fs.set("/logs/latest.log", SAMPLE_LOG);
  fs.set(
    "/plugins/README.txt",
    "Drop your plugin .jar files in this directory.\n"
  );
  fs.set(
    "/world/level.dat",
    "(binary NBT — not displayed in text editor)"
  );
  return fs;
}

function getFs(uuid: string): Map<string, string> {
  if (!virtualFs.has(uuid)) virtualFs.set(uuid, buildFs(uuid));
  return virtualFs.get(uuid)!;
}

// ── Boot sequence ─────────────────────────────────────────────────────────────
// Staggered lines — index is delay-in-ms from boot start

const BOOT_SEQUENCE: [number, string][] = [
  [0,    "Starting Paper server..."],
  [200,  "Loading libraries, please wait..."],
  [800,  `${ts()} INFO]: Starting minecraft server version 1.21.4`],
  [900,  `${ts()} INFO]: Loading properties`],
  [950,  `${ts()} INFO]: This server is running Paper version git-Paper-196 (MC: 1.21.4) (implementing API version 1.21.4-R0.1-SNAPSHOT)`],
  [1000, `${ts()} INFO]: Server Ping Player Sample Count: 12`],
  [1050, `${ts()} INFO]: Using 4 threads for Netty based IO`],
  [1100, `${ts()} INFO]: [Paper] Loading Paper patches`],
  [1300, `${ts()} INFO]: Default game type: SURVIVAL`],
  [1400, `${ts()} INFO]: Generating keypair`],
  [1500, `${ts()} INFO]: Starting Minecraft server on *:25565`],
  [1600, `${ts()} INFO]: Using epoll channel type`],
  [1700, `${ts()} INFO]: Preparing level 'world'`],
  [1800, `${ts()} INFO]: Preparing start region for dimension minecraft:overworld`],
  [2000, `${ts()} INFO]: Preparing spawn area: 0%`],
  [2300, `${ts()} INFO]: Preparing spawn area: 24%`],
  [2600, `${ts()} INFO]: Preparing spawn area: 48%`],
  [2900, `${ts()} INFO]: Preparing spawn area: 72%`],
  [3100, `${ts()} INFO]: Preparing spawn area: 96%`],
  [3200, `${ts()} INFO]: Time elapsed: 1521 ms`],
  [3300, `${ts()} INFO]: Preparing start region for dimension minecraft:the_nether`],
  [3700, `${ts()} INFO]: Time elapsed: 421 ms`],
  [3800, `${ts()} INFO]: Preparing start region for dimension minecraft:the_end`],
  [4100, `${ts()} INFO]: Time elapsed: 312 ms`],
  [4200, `${ts()} INFO]: Running delayed init tasks`],
  [4400, `${ts()} INFO]: Done (4.4s)! For help, type "help"`],
  [4500, `${ts()} INFO]: Timings Reset`],
];

// ── Stop sequence ─────────────────────────────────────────────────────────────

const STOP_SEQUENCE: [number, string][] = [
  [0,    `${ts()} INFO]: Stopping the server`],
  [100,  `${ts()} INFO]: Stopping server`],
  [200,  `${ts()} INFO]: Saving players`],
  [400,  `${ts()} INFO]: Saving worlds`],
  [600,  `${ts()} INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld`],
  [800,  `${ts()} INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_nether`],
  [1000, `${ts()} INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_end`],
  [1200, `${ts()} INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved`],
  [1400, `${ts()} INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved`],
  [1500, `${ts()} INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved`],
  [1600, `${ts()} INFO]: Flushing Chunk IO`],
  [1700, `${ts()} INFO]: Closing Thread Pool`],
  [1800, `${ts()} INFO]: Closing Server`],
];

// ── Stat tick ─────────────────────────────────────────────────────────────────

function startTick(uuid: string) {
  const s = getServer(uuid);
  if (s.tickInterval) return;

  s.tickInterval = setInterval(() => {
    const srv = getServer(uuid);
    if (srv.status === "offline") {
      clearInterval(srv.tickInterval!);
      srv.tickInterval = null;
      return;
    }
    if (srv.status === "running") {
      // CPU: drifts between 8–35 %, occasional spike to 60 %
      const spike = Math.random() < 0.05;
      srv.cpu = spike
        ? 40 + Math.random() * 20
        : Math.max(8, Math.min(35, srv.cpu + (Math.random() - 0.48) * 4));
      // RAM: slowly climbs from 512 MB, cap at 1.8 GB
      srv.memBytes = Math.min(
        1.8e9,
        Math.max(
          256e6,
          srv.memBytes + (Math.random() - 0.3) * 8e6
        )
      );
      // Network: small random deltas
      srv.netRx += Math.round(Math.random() * 4096);
      srv.netTx += Math.round(Math.random() * 2048);
    }
  }, 1000);
}

// ── Power actions ─────────────────────────────────────────────────────────────

async function doStart(uuid: string) {
  const s = getServer(uuid);
  if (s.status !== "offline") return;

  s.status = "starting";
  s.cpu = 5;
  s.memBytes = 128e6;

  startTick(uuid);

  // Replay boot sequence with proper delays
  const base = Date.now();
  for (const [delayMs, line] of BOOT_SEQUENCE) {
    const wait = delayMs - (Date.now() - base);
    if (wait > 0) await delay(wait);
    pushLog(uuid, line);

    // Ramp CPU and RAM as the server "loads"
    const progress = delayMs / 4500;
    s.cpu = 5 + progress * 75 * (0.8 + Math.random() * 0.4);
    s.memBytes = 128e6 + progress * 384e6;
  }

  s.status = "running";
  s.startedAt = Date.now();
  s.cpu = 15 + Math.random() * 10;
  s.memBytes = 512e6 + Math.random() * 64e6;
}

async function doStop(uuid: string, kill = false) {
  const s = getServer(uuid);
  if (s.status === "offline") return;

  s.status = "stopping";

  if (kill) {
    await delay(300);
    pushLog(uuid, `${ts()} INFO]: Server killed`);
  } else {
    const base = Date.now();
    for (const [delayMs, line] of STOP_SEQUENCE) {
      const wait = delayMs - (Date.now() - base);
      if (wait > 0) await delay(wait);
      pushLog(uuid, line);
    }
  }

  s.status = "offline";
  s.cpu = 0;
  s.memBytes = 0;
  s.netRx = 0;
  s.netTx = 0;
  s.startedAt = null;
  s.onlinePlayerCount = 0;

  if (s.tickInterval) {
    clearInterval(s.tickInterval);
    s.tickInterval = null;
  }
}

// ── Command handling ──────────────────────────────────────────────────────────

const HELP_TEXT = [
  `${ts()} INFO]: --- Showing help page 1 of 1 (/help <page>) ---`,
  `${ts()} INFO]: /difficulty [difficulty]`,
  `${ts()} INFO]: /gamemode <mode> [player]`,
  `${ts()} INFO]: /give <target> <item> [count]`,
  `${ts()} INFO]: /help [page | command name]`,
  `${ts()} INFO]: /kick <target> [reason]`,
  `${ts()} INFO]: /list [uuids]`,
  `${ts()} INFO]: /op <targets>`,
  `${ts()} INFO]: /say <message>`,
  `${ts()} INFO]: /stop`,
  `${ts()} INFO]: /time <set|add|query> <value>`,
  `${ts()} INFO]: /tps`,
  `${ts()} INFO]: /weather <clear|rain|thunder> [duration]`,
  `${ts()} INFO]: /whitelist <on|off|add|remove|list|reload>`,
];

async function handleCommand(uuid: string, raw: string) {
  const s = getServer(uuid);
  if (s.status !== "running") {
    pushLog(uuid, `${ts()} WARN]: Server is not running`);
    return;
  }

  const cmd = raw.trim();
  pushLog(uuid, `> ${cmd}`);

  const parts = cmd.replace(/^\//, "").split(/\s+/);
  const base = parts[0]?.toLowerCase() ?? "";

  switch (base) {
    case "list": {
      const n = s.onlinePlayerCount;
      pushLog(
        uuid,
        `${ts()} INFO]: There are ${n} of a max of 20 players online:${n > 0 ? " Steve" : ""}`
      );
      break;
    }
    case "help": {
      for (const line of HELP_TEXT) pushLog(uuid, line);
      break;
    }
    case "tps": {
      const tps = (19.5 + Math.random() * 0.5).toFixed(2);
      pushLog(uuid, `${ts()} INFO]: TPS from last 1m, 5m, 15m: ${tps}, ${tps}, ${tps}`);
      break;
    }
    case "version": {
      pushLog(
        uuid,
        `${ts()} INFO]: This server is running Paper version git-Paper-196 (MC: 1.21.4) (implementing API version 1.21.4-R0.1-SNAPSHOT)`
      );
      break;
    }
    case "say": {
      const msg = parts.slice(1).join(" ");
      pushLog(uuid, `${ts()} INFO]: [Server] ${msg}`);
      break;
    }
    case "time": {
      const sub = parts[1]?.toLowerCase();
      const val = parts[2]?.toLowerCase();
      if (sub === "set") {
        const ticks =
          val === "day" ? 1000
            : val === "noon" ? 6000
            : val === "night" ? 13000
            : val === "midnight" ? 18000
            : parseInt(val ?? "0", 10);
        pushLog(uuid, `${ts()} INFO]: Set the time to ${isNaN(ticks) ? 0 : ticks}`);
      } else if (sub === "query" || sub === "daytime") {
        pushLog(uuid, `${ts()} INFO]: The time is ${Math.floor(Math.random() * 24000)}`);
      } else {
        pushLog(uuid, `${ts()} INFO]: Usage: /time <set|add|query> <value>`);
      }
      break;
    }
    case "weather": {
      const sub = parts[1]?.toLowerCase();
      if (sub === "clear") pushLog(uuid, `${ts()} INFO]: Changing to clear weather`);
      else if (sub === "rain") pushLog(uuid, `${ts()} INFO]: Changing to rain weather`);
      else if (sub === "thunder") pushLog(uuid, `${ts()} INFO]: Changing to thunder weather`);
      else pushLog(uuid, `${ts()} INFO]: Usage: /weather <clear|rain|thunder>`);
      break;
    }
    case "op": {
      const target = parts[1];
      if (target) pushLog(uuid, `${ts()} INFO]: Made ${target} a server operator`);
      else pushLog(uuid, `${ts()} INFO]: Usage: /op <targets>`);
      break;
    }
    case "deop": {
      const target = parts[1];
      if (target) pushLog(uuid, `${ts()} INFO]: Made ${target} no longer a server operator`);
      else pushLog(uuid, `${ts()} INFO]: Usage: /deop <targets>`);
      break;
    }
    case "gamemode":
    case "gm": {
      const mode = parts[1];
      if (mode) pushLog(uuid, `${ts()} INFO]: Set own game mode to ${mode} Mode`);
      else pushLog(uuid, `${ts()} INFO]: Usage: /gamemode <mode> [player]`);
      break;
    }
    case "difficulty": {
      const d = parts[1];
      if (d) pushLog(uuid, `${ts()} INFO]: The difficulty has been set to ${d}`);
      else pushLog(uuid, `${ts()} INFO]: The difficulty is currently ${["peaceful","easy","normal","hard"][1]}`);
      break;
    }
    case "stop": {
      // Trigger stop — don't await (fire & forget so the console still shows logs)
      doStop(uuid, false).catch(() => {});
      break;
    }
    case "": {
      break;
    }
    default: {
      pushLog(
        uuid,
        `${ts()} ERROR]: Unknown or incomplete command, see '/help' for a list of commands`
      );
    }
  }
}

// ── Directory listing ─────────────────────────────────────────────────────────

function listDir(uuid: string, directory: string): WingsDirectoryContents {
  const fs = getFs(uuid);
  const prefix = directory === "/" ? "/" : directory.replace(/\/$/, "") + "/";

  const seen = new Set<string>();
  const entries: WingsDirectoryContents["data"] = [];

  for (const [path] of Array.from(fs)) {
    if (!path.startsWith(prefix)) continue;
    const rest = path.slice(prefix.length);
    if (!rest) continue;

    const name = rest.split("/")[0] ?? "";
    if (!name || name === ".dirmarker" || seen.has(name)) continue;
    seen.add(name);

    const isFile = !rest.includes("/");
    const content = isFile ? (fs.get(path) ?? "") : "";
    entries.push({
      name,
      mode: isFile ? "-rw-r--r--" : "drwxr-xr-x",
      size: isFile ? Buffer.byteLength(content, "utf8") : 0,
      is_file: isFile,
      is_symlink: false,
      is_editable: isFile,
      mimetype: isFile ? detectMime(name) : "inode/directory",
      created_at: new Date(Date.now() - 86400_000).toISOString(),
      modified_at: new Date().toISOString(),
    });
  }

  return { object: "list", data: entries };
}

function detectMime(filename: string): string {
  const ext = filename.split(".").pop()?.toLowerCase() ?? "";
  const map: Record<string, string> = {
    properties: "text/plain",
    yml: "text/yaml",
    yaml: "text/yaml",
    json: "application/json",
    toml: "application/toml",
    log: "text/plain",
    txt: "text/plain",
    sh: "text/x-sh",
    jar: "application/java-archive",
  };
  return map[ext] ?? "application/octet-stream";
}

// ── Public API ────────────────────────────────────────────────────────────────

export const simulator = {
  // ── Resources snapshot ────────────────────────────────────────────────────
  getResources(uuid: string): WingsServerState {
    const s = getServer(uuid);
    const uptime = s.startedAt ? Date.now() - s.startedAt : 0;
    return {
      object: "server_state",
      attributes: {
        current_state: s.status,
        is_suspended: false,
        resources: {
          memory_bytes: Math.round(s.memBytes),
          cpu_absolute: parseFloat(s.cpu.toFixed(2)),
          disk_bytes: s.diskBytes,
          network_rx_bytes: s.netRx,
          network_tx_bytes: s.netTx,
          uptime,
        },
      },
    };
  },

  // ── Power actions ─────────────────────────────────────────────────────────
  async power(uuid: string, action: PowerAction): Promise<void> {
    switch (action) {
      case "start":
        doStart(uuid).catch(() => {});
        break;
      case "stop":
        doStop(uuid, false).catch(() => {});
        break;
      case "kill":
        doStop(uuid, true).catch(() => {});
        break;
      case "restart":
        doStop(uuid, false)
          .then(() => delay(1000))
          .then(() => doStart(uuid))
          .catch(() => {});
        break;
    }
  },

  // ── Console auth (used by wings/client.ts) ────────────────────────────────
  getConsoleAuth(uuid: string): WingsConsoleAuth {
    return {
      token: `sim-${uuid}`,
      socket: `ws://localhost:${process.env.PORT ?? 3000}/api/servers/${uuid}/console/ws`,
    };
  },

  // ── Command handling ──────────────────────────────────────────────────────
  handleCommand(uuid: string, command: string): void {
    handleCommand(uuid, command).catch(() => {});
  },

  // ── Log replay ────────────────────────────────────────────────────────────
  getRecentLogs(uuid: string): string[] {
    return [...(logBuffers.get(uuid) ?? [])];
  },

  // ── File system ───────────────────────────────────────────────────────────
  listDirectory(uuid: string, directory: string): WingsDirectoryContents {
    return listDir(uuid, directory || "/");
  },

  readFile(uuid: string, file: string): string {
    return getFs(uuid).get(file) ?? "";
  },

  writeFile(uuid: string, file: string, contents: string): void {
    getFs(uuid).set(file, contents);
  },

  deleteFiles(uuid: string, root: string, files: string[]): void {
    const fs = getFs(uuid);
    for (const f of files) {
      const fullPath = root === "/" ? `/${f}` : `${root}/${f}`;
      fs.delete(fullPath);
    }
  },

  // ── Backups ───────────────────────────────────────────────────────────────
  createBackup(uuid: string, backupUuid: string): WingsBackup {
    return {
      uuid: backupUuid,
      is_successful: true,
      checksum: "abc123def456",
      checksum_type: "sha256",
      file_size: Math.round((40 + Math.random() * 60) * 1024 * 1024),
      parts: null,
      created_at: new Date().toISOString(),
    };
  },

  deleteBackup(_uuid: string, _backupUuid: string): void {
    // no-op
  },

  // ── File operations ───────────────────────────────────────────────────────
  renameFiles(uuid: string, root: string, files: Array<{ from: string; to: string }>): void {
    const fs = getFs(uuid);
    for (const { from, to } of files) {
      const fromPath = root === "/" ? `/${from}` : `${root}/${from}`;
      const toPath = root === "/" ? `/${to}` : `${root}/${to}`;
      const content = fs.get(fromPath);
      if (content !== undefined) {
        fs.set(toPath, content);
        fs.delete(fromPath);
      }
    }
  },

  createDirectory(uuid: string, name: string, parentDir: string): void {
    const fs = getFs(uuid);
    // Store a hidden marker so the directory appears in listings
    const dirPath = parentDir === "/" ? `/${name}` : `${parentDir}/${name}`;
    fs.set(`${dirPath}/.dirmarker`, "");
  },

  uploadFile(uuid: string, directory: string, filename: string, contents: string): void {
    const fs = getFs(uuid);
    const path = directory === "/" ? `/${filename}` : `${directory}/${filename}`;
    fs.set(path, contents);
  },

  reinstall(uuid: string): void {
    // Wipe virtual FS back to seed state
    virtualFs.delete(uuid);
    logBuffers.delete(uuid);
    const s = servers.get(uuid);
    if (s) {
      if (s.tickInterval) clearInterval(s.tickInterval);
      servers.delete(uuid);
    }
  },

  // ── Console event subscription ────────────────────────────────────────────
  onConsole(uuid: string, cb: (line: string) => void): () => void {
    let set = consoleListeners.get(uuid);
    if (!set) {
      set = new Set();
      consoleListeners.set(uuid, set);
    }
    set.add(cb);
    return () => set!.delete(cb);
  },
};
