#!/usr/bin/env node
/**
 * Cross-platform dev bootstrap. Works on macOS, Linux, and Windows (WSL2 / Docker Desktop).
 * Replaces shell scripts — pure Node.js, no bash required.
 *
 * What it does:
 *   1. Verifies Docker is running
 *   2. Generates .env.local with safe defaults if it doesn't exist
 *   3. Starts Postgres + Redis via docker-compose.dev.yml
 *   4. Waits for Postgres to accept connections
 *   5. Runs Prisma migrations (idempotent)
 *   6. Seeds the database (idempotent upserts)
 *   7. Starts the Next.js dev server
 */

import { execSync, spawn } from "node:child_process";
import { existsSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { randomBytes } from "node:crypto";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");

// ── Logging ──────────────────────────────────────────────────────────────────
const c = {
  reset: "\x1b[0m",
  cyan: "\x1b[36m",
  green: "\x1b[32m",
  yellow: "\x1b[33m",
  red: "\x1b[31m",
  bold: "\x1b[1m",
};

const log = (msg) => console.log(`${c.cyan}[dev]${c.reset} ${msg}`);
const ok = (msg) => console.log(`${c.green}[ok]${c.reset}  ${msg}`);
const warn = (msg) => console.warn(`${c.yellow}[warn]${c.reset} ${msg}`);
const die = (msg) => {
  console.error(`${c.red}[error]${c.reset} ${msg}`);
  process.exit(1);
};

// ── Helpers ───────────────────────────────────────────────────────────────────
function run(cmd, opts = {}) {
  execSync(cmd, { cwd: ROOT, stdio: "inherit", ...opts });
}

function tryRun(cmd) {
  try {
    execSync(cmd, { cwd: ROOT, stdio: "pipe" });
    return true;
  } catch {
    return false;
  }
}

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

// ── Docker checks ─────────────────────────────────────────────────────────────
function checkDocker() {
  if (!tryRun("docker info")) {
    die(
      "Docker is not running.\n" +
        "       Please start Docker Desktop (or the Docker daemon) and try again."
    );
  }
  ok("Docker is running");
}

function getComposeCmd() {
  if (tryRun("docker compose version")) return "docker compose";
  if (tryRun("docker-compose version")) return "docker-compose";
  die(
    "Docker Compose not found.\n" +
      "       Install Docker Desktop — it includes Compose v2."
  );
}

// ── .env.local generation ─────────────────────────────────────────────────────
function ensureEnvLocal() {
  const envPath = join(ROOT, ".env.local");
  if (existsSync(envPath)) return;

  log("Generating .env.local with development defaults...");
  const secret = randomBytes(32).toString("hex");

  const lines = [
    "# Auto-generated by npm run dev:local — safe to edit",
    `DATABASE_URL=postgresql://hobby:hobby@localhost:5432/hobby_panel`,
    `REDIS_URL=redis://localhost:6379`,
    `AUTH_SECRET=${secret}`,
    `MOCK_WINGS=true`,
    `APP_URL=http://localhost:3000`,
    `NODE_ENV=development`,
  ];

  writeFileSync(envPath, lines.join("\n") + "\n");
  ok("Created .env.local");
}

// ── Wait for Postgres ─────────────────────────────────────────────────────────
async function waitForPostgres(composeCmd, maxWaitSecs = 60) {
  log("Waiting for Postgres to be ready...");
  const deadline = Date.now() + maxWaitSecs * 1000;

  while (Date.now() < deadline) {
    if (
      tryRun(
        `${composeCmd} -f docker-compose.dev.yml exec -T postgres pg_isready -U hobby -d hobby_panel`
      )
    ) {
      ok("Postgres is ready");
      return;
    }
    await sleep(1000);
  }

  die("Postgres did not become ready within 60 seconds. Check Docker logs.");
}

// ── Main ──────────────────────────────────────────────────────────────────────
async function main() {
  console.log(
    `\n${c.bold}${c.cyan}HobbyPanel${c.reset} — local dev environment\n`
  );

  checkDocker();
  const composeCmd = getComposeCmd();
  ensureEnvLocal();

  log("Starting Postgres and Redis...");
  run(`${composeCmd} -f docker-compose.dev.yml up -d`);
  ok("Containers started");

  await waitForPostgres(composeCmd);

  log("Running database migrations...");
  // --skip-generate avoids re-generating the client here; we run that next
  const migrationsDir = join(ROOT, "prisma", "migrations");
  if (existsSync(migrationsDir)) {
    // Migrations already exist — apply any pending ones non-interactively
    run("npx prisma migrate deploy");
  } else {
    // First run — create the initial migration
    run("npx prisma migrate dev --name init --skip-generate");
  }
  ok("Migrations applied");

  log("Generating Prisma client...");
  run("npx prisma generate");
  ok("Prisma client ready");

  log("Seeding database...");
  run("npx tsx prisma/seed.ts");
  ok("Database seeded");

  console.log(`
${c.green}${c.bold}Ready!${c.reset}

  ${c.bold}URL:${c.reset}      http://localhost:3000
  ${c.bold}Admin:${c.reset}    admin@local.test / password
  ${c.bold}User:${c.reset}     user@local.test  / password
  ${c.bold}Wings:${c.reset}    Mock mode (MOCK_WINGS=true)

`);

  // Spawn the custom server (Next.js + WebSocket support).
  // tsx watch restarts if server.ts or ws-handler changes; Next.js HMR
  // handles all page/route hot-reloads without a full restart.
  const isWindows = process.platform === "win32";
  const next = spawn(
    isWindows ? "npx.cmd" : "npx",
    ["tsx", "watch", "--clear-screen=false", "server.ts"],
    { cwd: ROOT, stdio: "inherit" }
  );

  const shutdown = () => {
    next.kill();
    process.exit(0);
  };
  process.on("SIGINT", shutdown);
  process.on("SIGTERM", shutdown);
  next.on("exit", (code) => process.exit(code ?? 0));
}

main().catch((err) => die(err.message));
